# 构建时自动生成 BuildInfo.g.cs：版本号 = 构建日期 + 推送号（git 短哈希）
# 由 WindowsFormsApplication1.csproj 的 GenerateBuildInfo 目标在编译前调用
param([string]$projDir)
$ErrorActionPreference = 'SilentlyContinue'

$hash = ''
try {
    $hash = (& git -C $projDir rev-parse --short HEAD 2>$null | Out-String).Trim()
}
catch { }
if ([string]::IsNullOrWhiteSpace($hash)) { $hash = 'nogit' }

$now = Get-Date
$ver = $now.ToString('yyyy.MM.dd') + '+' + $hash
$bt = $now.ToString('yyyy-MM-dd HH:mm:ss')

$content = @"
// <auto-generated> 构建时自动生成（版本 = 构建日期 + 推送号/git 短哈希）；请勿手工修改。
// 生成脚本：tools/gen-buildinfo.ps1（csproj GenerateBuildInfo 目标在编译前调用）。
namespace WindowsFormsApplication1
{
    internal static class BuildInfo
    {
        public const string Version = "$ver";
        public const string BuildTime = "$bt";
    }
}
"@

Set-Content -Path (Join-Path $projDir 'BuildInfo.g.cs') -Value $content -Encoding UTF8
Write-Host ("BuildInfo.g.cs 已生成: " + $ver)
