// <auto-generated> 鏋勫缓鏃惰嚜鍔ㄧ敓鎴愶紙鐗堟湰 = 鏋勫缓鏃ユ湡 + 鎺ㄩ€佸彿/git 鐭搱甯岋級锛涜鍕挎墜宸ヤ慨鏀广€?
// 鐢熸垚鑴氭湰锛歵ools/gen-buildinfo.ps1锛坈sproj GenerateBuildInfo 鐩爣鍦ㄧ紪璇戝墠璋冪敤锛夈€?
namespace WindowsFormsApplication1
{
    internal static class BuildInfo
    {
        public const string Version = "2026.09.20+292138f";
        public const string BuildTime = "2026-09-20 16:26:43";
    }
}
